import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {
  ClerkProvider
  
} from '@clerk/nextjs'
import { FloatingNav } from "@/components/ui/floating-navbar";
import { navItems } from "@/constants";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bablue 1.0- The AI Assistant",  
  description: "Generated by create next app",
  favicon:'/icons/logo-og.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/icons/logo-og.png" type="image/png" />
      </head>
    <ClerkProvider
    appearance={{
      layout:{
        logoImageUrl:'/icons/logo-og.png',
        socialButtonsVariant:'iconButton'
      },
      variables:{
        colorText:'#FFF',
        colorPrimary:"#0E78F9",
        colorBackground:'#1c1f2e',
        colorInputBackground:'#252a41',
        colorInputText:'#fff'
      }
    }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <FloatingNav navItems={navItems} />

            {children}
          </ThemeProvider>
      </body>
    </ClerkProvider>
    </html> 
  );
}
